export const balance = {
  version: 11,
  baseClick: 1,
  offlineCap: 8 * 3600,
  autosaveSeconds: 10,
  focusPerClick: 4,
  focusDecay: 7,
  deepWorkSeconds: 10,
  employeeBaseCost: 1500,
  employeeCostMultiplier: 1.65,
  employeeWork: 5,
  employeeSalary: 2.8,
  employeeLevelCost: 700,
  employeeLevelMultiplier: 1.65,
  maxEmployees: [1, 3, 6],
  officeCosts: [0, 5000, 30000],
  officeExpenses: [0, 9, 32],
  upgradeCostMultiplier: 1.85,
  maxUpgradeLevel: 5,
  maxValue: 1e100,
} as const;
export const projects = [
  {
    id: 'landing',
    work: 100,
    pay: 100,
    xp: 10,
    reputation: 1,
    required: 0,
    previous: null,
    deliveries: 0,
    employees: 0,
    employeeLevel: 1,
    office: 0,
  },
  {
    id: 'restaurant',
    work: 800,
    pay: 1000,
    xp: 35,
    reputation: 3,
    required: 5,
    previous: 'landing',
    deliveries: 3,
    employees: 1,
    employeeLevel: 1,
    office: 0,
  },
  {
    id: 'shop',
    work: 4000,
    pay: 6500,
    xp: 110,
    reputation: 8,
    required: 18,
    previous: 'restaurant',
    deliveries: 3,
    employees: 2,
    employeeLevel: 2,
    office: 1,
  },
  {
    id: 'app',
    work: 22000,
    pay: 40000,
    xp: 260,
    reputation: 20,
    required: 45,
    previous: 'shop',
    deliveries: 3,
    employees: 3,
    employeeLevel: 3,
    office: 2,
  },
] as const;
export const upgrades = [
  { id: 'coffee', cost: 100, click: 1, multiplier: 0, category: 'equipment' },
  { id: 'keyboard', cost: 350, click: 3, multiplier: 0, category: 'equipment' },
  { id: 'monitor', cost: 850, click: 0, multiplier: 0.1, category: 'equipment' },
  { id: 'laptop', cost: 1700, click: 0, multiplier: 0.2, category: 'equipment' },
  { id: 'fiber', cost: 2400, click: 0, multiplier: 0.15, category: 'technology' },
] as const;
export type UpgradeId = (typeof upgrades)[number]['id'];
export type ProjectId = (typeof projects)[number]['id'];
