// Agency contracts unlock products; operating them never fabricates contract deliveries.
export const operationIds = ['sites', 'menus', 'commerce', 'apps', 'saas'] as const;
export type OperationId = (typeof operationIds)[number];
export const operationBalance = {
  maxLevel: 100,
  costGrowth: 1.1,
  milestones: [10, 25, 50, 75, 100],
} as const;
export const operations = [
  {
    id: 'sites',
    cost: 2500,
    cycle: 15,
    payout: 45,
    automation: 8000,
    project: 'landing',
    deliveries: 5,
    office: 0,
    developers: 0,
    developerLevel: 1,
    portfolio: 0,
  },
  {
    id: 'menus',
    cost: 18000,
    cycle: 45,
    payout: 450,
    automation: 65000,
    project: 'restaurant',
    deliveries: 3,
    office: 1,
    developers: 0,
    developerLevel: 1,
    portfolio: 0,
  },
  {
    id: 'commerce',
    cost: 140000,
    cycle: 120,
    payout: 4500,
    automation: 550000,
    project: 'shop',
    deliveries: 3,
    office: 1,
    developers: 0,
    developerLevel: 1,
    portfolio: 0,
  },
  {
    id: 'apps',
    cost: 1800000,
    cycle: 300,
    payout: 60000,
    automation: 7000000,
    project: 'app',
    deliveries: 2,
    office: 2,
    developers: 1,
    developerLevel: 10,
    portfolio: 0,
  },
  {
    id: 'saas',
    cost: 35000000,
    cycle: 900,
    payout: 1200000,
    automation: 120000000,
    project: 'app',
    deliveries: 15,
    office: 2,
    developers: 2,
    developerLevel: 10,
    portfolio: 100,
  },
] as const;
